baseURL = "https://erictalviste.com/"
enableRobotsTXT = "true"
languageCode = "en-us"
summaryLength = "10"
theme = "kross-hugo"
title = "ET | Eric Talviste Portfolio"
[[menu.main]]
URL = "about"
name = "About"
weight = 1
[[menu.main]]
URL = "portfolio"
name = "Portfolio"
weight = 3
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 4
[params]
address = "Tallinn, Harjumaa, Estonia"
author = "Eric Talviste"
copyright = ""
description = "Erictalviste is my Portfolio website! Web developer and designer Eric Talviste resides in these virtual walls, apps, designs, abouts etc."
email = "eric.talviste@gmail.com"
google_analytics_id = "UA-166928853-2"
home = "Home"
logo = "/images/et-white.svg"
phone = "+372 53021455"
theme_color = "#145DA0"
[params.contact]
enable = true
form_action = "https://formspree.io/xpzypplo"
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/slick/slick.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"
[[params.plugins.js]]
URL = "plugins/shuffle/shuffle.min.js"
[params.preloader]
enable = true
preloader = ""
[[params.social]]
URL = "https://www.linkedin.com/in/erictalviste/"
icon = "ti-linkedin"
[[params.social]]
URL = "https://github.com/EricTalv"
icon = "ti-github"
[[params.social]]
URL = "https://dribbble.com/EricTalv"
icon = "ti-dribbble"
