baseURL = "https://etweb.netlify.app/"
languageCode = "en-us"
summaryLength = "10"
theme = "kross-hugo"
title = "ET | Eric Talviste Portfolio"
[[menu.main]]
URL = "http://etxp.tk/"
name = "blog"
weight = "4"
[[menu.main]]
URL = "about"
name = "About"
weight = 1
[[menu.main]]
URL = "portfolio"
name = "Portfolio"
weight = 3
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 4
[params]
address = "Tallinn, Harjumaa, Estonia"
author = "Eric Talviste"
copyright = "Copyright &copy; 2020 a theme by [gethugothemes](https://gethugothemes.com)"
description = "Eric Talviste, Portfolio"
email = "erictalviste@gmail.com"
google_analytics_id = ""
home = "Home"
logo = "images/staggered.svg"
phone = "+372 53021455"
theme_color = "#145DA0"
[params.contact]
enable = true
form_action = "#"
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/slick/slick.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"
[[params.plugins.js]]
URL = "plugins/shuffle/shuffle.min.js"
[params.preloader]
enable = true
preloader = ""
[[params.social]]
URL = "https://github.com/EricTalv"
icon = "ti-github"
[[params.social]]
URL = "https://dribbble.com/EricTalv"
icon = "ti-dribbble"
